### ISSUE TITLE
The end point for china timeseries is not returning data

### ISSUE THREAD

**Issue by phptuts** [NovelCOVID/API#138] opened 2020-03-24 05:07 UTC
The end point for the china timeline series is not returning data.

https://corona.lmao.ninja/historical/china
```json
{
standardizedCountryName: "china",
timeline: {
cases: { },
deaths: { },
recovered: { }
}
}

```

**Comment by ebwinters** [comment] 2020-03-24 05:14
yeah this is part of a bigger issue which I will fix tomorrow. our data source (Johns Hopkins) discontinued certain APis and features so we need to reprogram the endpoints

**Comment by phptuts** [comment] 2020-03-24 05:22
Thank you

**Comment by kw2019ltd** [comment] 2020-03-24 10:02
yes same here waiting thank you

**Comment by EliteDaMyth** [comment] 2020-03-24 13:49
closing.

**Closed by EliteDaMyth** 2020-03-24 13:49 UTC

**Comment by kw2019ltd** [comment] 2020-03-24 15:28
still getting empty result

{"standardizedCountryName":"china","timeline":{"cases":{},"deaths":{},"recovered":{}}}

**Comment by ebwinters** [comment] 2020-03-24 15:37
yesterday I said I'd fix it tomorrow and it's 10:30 AM. Give me a couple hours dude lol

**Comment by kw2019ltd** [comment] 2020-03-24 15:40
yeah sure i just saw the issue is closed :) take your time thanks
