### ISSUE TITLE
Endpoint is not working

### ISSUE THREAD

**Issue by ebwinters** [NovelCOVID/API#29] opened 2020-03-18 16:45 UTC
A query to the endpoint such as: https://corona.lmao.ninja/countries/usa returns plaintext `Country not found`

**Comment by benjamin-sommer** [comment] 2020-03-18 16:53
Same here.

**Comment by Solweigdev** [comment] 2020-03-18 17:36
Duplicate of #30

**Comment by silverhairs** [comment] 2020-03-18 17:49
Fixed

**Comment by EliteDaMyth** [comment] 2020-03-18 18:01
Fixed

**Closed by EliteDaMyth** 2020-03-18 18:01 UTC

**Comment by ebwinters** [comment] 2020-03-19 00:59
Happening again rn
