### ISSUE TITLE
Key mismatch in /states endpoint

### ISSUE THREAD

**Issue by siaw23** [NovelCOVID/API#140] opened 2020-03-24 12:12 UTC
I'm wondering the validity of this information  on the `/states` endpoint

`{"state":"Maryland","cases":288,"todayCases":0,"deaths":3,"todayDeaths":0,"recovered":281,"active":0}`

The number of recovered people is 281, this is not correct I think because in the whole of the States only about 600 people have recovered.

In fact, all ACTIVE keys  on `https://corona.lmao.ninja/states` are `0`

I think RECOVERED is swapped for ACTIVE.

**Comment by kvenn** [comment] 2020-03-24 12:47
The scraper broke because the columns changed again. The table removed recovered.

https://www.worldometers.info/coronavirus/country/us/

**Comment by JamesShelley** [comment] 2020-03-24 13:22
@EliteDaMyth just confirmed a fix for this is one the way  - https://github.com/NovelCOVID/API/pull/141 👍

**Comment by EliteDaMyth** [comment] 2020-03-24 13:23
it is pushed to the repo. it is not yet on the main API yet. We are testing some stuff rn so it can take a while for now :)

**Comment by EliteDaMyth** [comment] 2020-03-24 13:24
@all-contributors please add @JamesShelley for review

**Closed by EliteDaMyth** 2020-03-24 13:23 UTC
